name: check-commit

on: push

jobs:
  check-commit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
        check-latest: true
    - name: install dependencies
      run: yarn
    - name: lint
      run: yarn lint
    - name: tsc
      run: yarn tsc
    - name: test
      run: yarn test
    - name: test
      run: yarn test
