name: deploy-demo

on:
  push:
    branches:
      - master

jobs:
  dev-deploy:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: install dependencies
        run: yarn
      - name: build
        run: yarn build
        env:
          REACT_APP_IS_DEMO: true
      - name: upload
        run: aws s3 sync build/. s3://demo.recap.dev/ --delete --exclude '*.txt' --cache-control 'max-age=31104000'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: upload
        run: aws s3 sync build/. s3://demo.recap.dev/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: invalidate cache
        run: aws cloudfront create-invalidation --distribution-id E1A6F7V8MVO0V2 --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

